# Generated by Django 4.0.1 on 2022-01-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_url', models.CharField(max_length=120)),
                ('cover', models.CharField(max_length=120)),
                ('movie', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('mood', models.CharField(default='Neutral', max_length=10)),
            ],
        ),
    ]
